services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    command: postgres -c wal_level=replica -c max_wal_senders=3 -c hot_standby=on
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh

  healthcheck-pg1:
    build:
      context: ./postgres
      dockerfile: Dockerfile.healthcheck
    environment:
      PGPASSWORD: admin
    network_mode: "service:postgres"
    depends_on:
      - postgres

  postgres_replica:
    image: postgres:16-alpine
    user: postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPASSWORD: admin
    ports:
      - '5433:5432'
    entrypoint: /entrypoint-replica.sh
    volumes:
      - pgdata_replica:/var/lib/postgresql/data
      - ./postgres/init-replica.sh:/entrypoint-replica.sh
    depends_on:
      - postgres

  healthcheck-pg2:
    build:
      context: ./postgres
      dockerfile: Dockerfile.healthcheck
    environment:
      PGPASSWORD: admin
    network_mode: "service:postgres_replica"
    depends_on:
      - postgres_replica

  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - '5000:5000'
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - postgres
      - postgres_replica

  failover-monitor:
    image: postgres:16-alpine
    entrypoint: /failover.sh
    environment:
      PGPASSWORD: admin
    volumes:
      - ./postgres/failover.sh:/failover.sh
    depends_on:
      - postgres
      - postgres_replica

  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: haproxy
      DB_PORT: 5000
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: ecommerce
    depends_on:
      - haproxy

volumes:
  pgdata:
  pgdata_replica:
