global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'url-shortener'
    static_configs:
      - targets: ['app1:3000', 'app2:3000', 'app3:3000']
  
  - job_name: 'patroni'
    metrics_path: /metrics
    static_configs:
      - targets: ['pg1:8008', 'pg2:8008', 'pg3:8008']
